Allow change pause container image
awslabs/amazon-eks-ami pull request #1527
Opened 2023-11-23 09:23 UTC by DingGGu

**Issue #1514, if available:**

**Description of changes:**
- Pause container image can be change.
- Changed to not use the ECR API if it is not ECR.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Testing Done**
- Add test for pause-container

*[See this guide for recommended testing for PRs.](../doc/CONTRIBUTING.md#testing-changes) Some tests may not apply. Completing tests and providing additional validation steps are not required, but it is recommended and may reduce review time and time to merge.*

2023-12-11 01:45 UTC, DingGGu commented on files/bootstrap.sh
>  PAUSE_CONTAINER="$PAUSE_CONTAINER_IMAGE:$PAUSE_CONTAINER_VERSION"
Okay, Applied that changes.

2023-12-11 17:59 UTC, cartermckinnon requested changes
Looks fine to me, just suggested a tweak to the flag doc.

2023-12-11 17:59 UTC, cartermckinnon commented on files/bootstrap.sh
> +  echo "--pause-container-image The full image to pull the pause container from"
```suggestion
  echo "--pause-container-image Image reference for the pause container image. If this flag is used, none of the other --pause-container-* flags take effect."
```

2023-12-11 18:00 UTC, cartermckinnon commented
@DingGGu you'll need to fix the lint findings, then I'll kick off integration tests 👍

2023-12-22 01:31 UTC, DingGGu commented
@cartermckinnon Is there anything else I need to change?

2024-05-08 17:38 UTC, closed without merging