fix/error-mkdir-nerdctl | mkdir creation fails when nerdctl is presen…
awslabs/amazon-eks-ami pull request #1786
Opened 2024-05-06 16:33 UTC by ricomasgu

mkdir creation fails when package nerdctl is already present in the ami.

**Issue #, if available:**

**Description of changes:**
Just add an if so it does not try to create it if it already exists.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Testing Done**
After this change, I could create my ami.  

*[See this guide for recommended testing for PRs.](../doc/CONTRIBUTING.md#testing-changes) Some tests may not apply. Completing tests and providing additional validation steps are not required, but it is recommended and may reduce review time and time to merge.*

2024-05-07 00:00 UTC, ndbaker1 requested changes

2024-05-07 00:00 UTC, ndbaker1 commented on templates/al2/provisioners/install-worker.sh
> +fi
oh 🥴 this probably should've been
```suggestion
sudo mkdir -p /etc/nerdctl
```

2024-05-09 17:53 UTC, ndbaker1 requested changes

2024-05-09 17:53 UTC, ndbaker1 commented on templates/al2/provisioners/install-worker.sh
> +sudo -p mkdir /etc/nerdctl
the `-p` flag was misplaced :d
```suggestion
sudo mkdir -p /etc/nerdctl
```

2024-05-10 18:32 UTC, cartermckinnon approved these changes

2024-05-10 18:59 UTC, ndbaker1 approved these changes

2024-05-10 19:00 UTC, merged