Log collector enhancements
awslabs/amazon-eks-ami pull request #993
Opened 2022-08-16 14:39 UTC by tzneal

**Description of changes:**

Collect XFS fragmentation as well as some additional network connectivity information.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Testing Done**

Verified on an EKS node.

*[See this guide for recommended testing for PRs.](https://github.com/awslabs/amazon-eks-ami/blob/master/CONTRIBUTING.md#testing-changes) Some tests may not apply. Completing tests and providing additional validation steps are not required, but it is recommended and may reduce review time and time to merge.*

2022-08-16 22:54 UTC, cartermckinnon requested changes

2022-08-16 22:54 UTC, cartermckinnon commented on log-collector-script/linux/eks-log-collector.sh
> +  timeout 75 ping -A -c 10 amazon.com > "${COLLECT_DIR}"/networking/ping_amazon.com.tzt
`.tzt` -> typo?

2022-08-16 22:54 UTC, cartermckinnon commented on log-collector-script/linux/eks-log-collector.sh
> +      timeout 75 curl -v --cacert /etc/kubernetes/pki/ca.crt "${API_SERVER}" >> ${COLLECT_DIR}"/networking/curl_api_server.txt" 2>&1
nit: pull the `certificate-authority` out of the kubeconfig like you did `API_SERVER`?

2022-08-16 23:52 UTC, tzneal commented on log-collector-script/linux/eks-log-collector.sh
> +  timeout 75 ping -A -c 10 amazon.com > "${COLLECT_DIR}"/networking/ping_amazon.com.tzt
Yup, good catch!

2022-08-17 16:57 UTC, cartermckinnon approved these changes

2022-08-23 19:21 UTC, merged